In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("./datas/beijing_tianqi/beijing_tianqi_2017-2019.csv")

In [3]:
df.head()

          ymd bWendu yWendu tianqi fengxiang fengli  aqi aqiInfo  aqiLevel
0  2017-01-01     5℃    -3℃    霾~晴        南风   1-2级  450    严重污染         6
1  2017-01-02     7℃    -6℃    晴~霾        南风   1-2级  246    重度污染         5
2  2017-01-03     5℃    -5℃      霾        南风   1-2级  320    严重污染         6
3  2017-01-04     6℃    -5℃      霾        北风   1-2级  360    严重污染         6
4  2017-01-05     2℃    -4℃      霾        北风   1-2级  280    重度污染         5

In [5]:
df["bWendu"] = df["bWendu"].map(lambda x : int(str(x).replace("℃", "")))
df["yWendu"] = df["yWendu"].map(lambda x : int(str(x).replace("℃", "")))

In [6]:
df.head()

          ymd  bWendu  yWendu tianqi fengxiang fengli  aqi aqiInfo  aqiLevel
0  2017-01-01       5      -3    霾~晴        南风   1-2级  450    严重污染         6
1  2017-01-02       7      -6    晴~霾        南风   1-2级  246    重度污染         5
2  2017-01-03       5      -5      霾        南风   1-2级  320    严重污染         6
3  2017-01-04       6      -5      霾        北风   1-2级  360    严重污染         6
4  2017-01-05       2      -4      霾        北风   1-2级  280    重度污染         5

### 同时添加温差，平均温度

In [7]:
def my_func(row):
    return row["bWendu"]-row["yWendu"], (row["bWendu"]+row["yWendu"])/2

df[["wencha", "avg"]] = df.apply(my_func, axis=1, result_type="expand")

In [8]:
df.head()

,ymd,bWendu,yWendu,tianqi,fengxiang,fengli,aqi,aqiInfo,aqiLevel,wencha,avg
0,2017-01-01,5,-3,霾~晴,南风,1-2级,450,严重污染,6,8.0,1.0
1,2017-01-02,7,-6,晴~霾,南风,1-2级,246,重度污染,5,13.0,0.5
2,2017-01-03,5,-5,霾,南风,1-2级,320,严重污染,6,10.0,0.0
3,2017-01-04,6,-5,霾,北风,1-2级,360,严重污染,6,11.0,0.5
4,2017-01-05,2,-4,霾,北风,1-2级,280,重度污染,5,6.0,-1.0